spring:
  application:
    name: fms-gateway

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

fms:
  instances:
    dir: instances-MD-CVRP-JSON
  engines:
    greedy:
      url: http://greedy-engine:8091
    random:
      url: http://random-engine:8092
    genetic:
      url: http://genetic-engine:8093

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
