name: Delivera

services:
  delivera-postgres:
    image: postgres:16
    container_name: delivera_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: delivera_dev
      POSTGRES_USER: delivera_user
      POSTGRES_PASSWORD: delivera_pass
    ports:
      - "5433:5432"
    volumes:
      - delivera_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U delivera_user -d delivera_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c 'max_connections=200'
    
  auth-postgres:
    image: postgres:16
    container_name: delivera_auth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: delivera_auth_dev
      POSTGRES_USER: delivera_auth_user
      POSTGRES_PASSWORD: delivera_auth_pass
    ports:
      - "5432:5432"
    volumes:
      - delivera_auth_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U delivera_auth_user -d delivera_auth_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c 'max_connections=200'

  data-postgres:
    image: postgres:16
    container_name: delivera_data_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: delivera_data_dev
      POSTGRES_USER: delivera_data_user
      POSTGRES_PASSWORD: delivera_data_pass
    ports:
      - "5434:5432"
    volumes:
      - delivera_data_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U delivera_data_user -d delivera_data_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c 'max_connections=200'

  auth-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.auth

    container_name: auth-service

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "9090:9090"
      - "9091:9091"

    expose:
      - "9091"
      - "9090"

    volumes:
      - ../auth-service/src/main/resources/keys:/app/keys:ro
      - ../auth-service/src/main/resources/certs:/app/certs:ro
  
  data-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.data

    container_name: data-service

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "9092:9092"
      - "9093:9093"

    expose:
      - "9092"
      - "9093"

    volumes:
      - ../data-service/src/main/resources/keys:/app/keys:ro
      - ../data-service/src/main/resources/certs:/app/certs:ro
  
  delivera-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.delivera

    container_name: delivera-service

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8080:8080"
      - "8081:8081"

    expose:
      - "8080"
      - "8081"

    volumes:
      - ../backend/src/main/resources/keys:/app/keys:ro
      - ../backend/src/main/resources/certs:/app/certs:ro
      

volumes:
  delivera_pg_data:
  delivera_auth_pg_data:
  delivera_data_pg_data:

