# ==========================
# Build
# ==========================
FROM maven:3.9-eclipse-temurin-21 AS build

WORKDIR /build

# Copiar código
COPY microservice-client-starter ./microservice-client-starter
COPY auth-service ./auth-service

# Instalar dependencia común
RUN cd microservice-client-starter && \
    mvn clean install -DskipTests

# Construir auth-service
RUN cd auth-service && \
    mvn clean package -DskipTests

# ==========================
# Runtime
# ==========================
FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /build/auth-service/target/*.jar app.jar

EXPOSE 9090
EXPOSE 9091

ENTRYPOINT ["java","-jar","app.jar"]