#!/usr/bin/env bash

set -euo pipefail

MODE="${1:-dev}"

OUTPUT="env/.env.compose.${MODE}"

readonly FILES=(
    "env/.env.certs"
    "env/.env.space"
    "env/.env.db.auth"
    "env/.env.db.data"
    "env/.env.db.delivera"
    "env/.env.jwt"
    "env/.env.${MODE}"
)

cat > "$OUTPUT" <<EOF
# ============================================================================
# GENERATED FILE
# ============================================================================
#
# Generated by generate-compose-env.sh
# Do not edit manually.
#
# Mode: ${MODE}
#
# ============================================================================

EOF

for file in "${FILES[@]}"; do

    [[ -f "$file" ]] || {
        echo "[ERROR] Missing configuration file: $file"
        exit 1
    }

    cat "$file" >> "$OUTPUT"

    echo "" >> "$OUTPUT"
    echo "" >> "$OUTPUT"

done

echo "[INFO] Generated $OUTPUT using mode: $MODE"