server {

    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /auth/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;


        proxy_ssl_certificate     /etc/nginx/certs/nginx-service.crt;
        proxy_ssl_certificate_key /etc/nginx/certs/nginx-service.key;

        proxy_ssl_trusted_certificate /etc/nginx/ca/ca.pem;

        proxy_ssl_verify on;

        rewrite ^/auth/(.*)$ /$1 break;
        proxy_pass https://auth-service;
    }

    location /data/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;

        proxy_ssl_certificate     /etc/nginx/certs/nginx-service.crt;
        proxy_ssl_certificate_key /etc/nginx/certs/nginx-service.key;

        proxy_ssl_trusted_certificate /etc/nginx/ca/ca.pem;

        proxy_ssl_verify on;

        rewrite ^/data/(.*)$ /$1 break;
        proxy_pass https://data-service;
    }

    location /delivera/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;

        proxy_ssl_certificate     /etc/nginx/certs/nginx-service.crt;
        proxy_ssl_certificate_key /etc/nginx/certs/nginx-service.key;

        proxy_ssl_trusted_certificate /etc/nginx/ca/ca.pem;

        proxy_ssl_verify on;

        rewrite ^/delivera/(.*)$ /$1 break;
        proxy_pass https://delivera-service;
    }

    location /public-api/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;

        proxy_ssl_certificate     /etc/nginx/certs/nginx-service.crt;
        proxy_ssl_certificate_key /etc/nginx/certs/nginx-service.key;

        proxy_ssl_trusted_certificate /etc/nginx/ca/ca.pem;

        proxy_ssl_verify on;

        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass https://delivera-service;
    }


}