spring:
  application:
    name: greedy-engine

server:
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
