spring:
  application:
    name: fms-routing-service

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

fms:
  instances:
    dir: instances-MD-CVRP
  service:
    url: http://localhost:8082
    solve-endpoint: /api/v1/fms/routing/solve

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
